Add GitHub folder
numixproject/numix-folders pull request #195
Opened 2020-10-18 09:46 UTC by drakkar1969

Add Github folder for all folder styles/sizes.

Uses `*-folder-system` as reference for placement of Github resource.

![numix-github](https://user-images.githubusercontent.com/18715287/96363906-69277880-1137-11eb-8b99-907d5498eef7.png)

2020-12-31 16:41 UTC, palob requested changes
Hi, thank you for this big chunk of work and sorry I'm so late with my review.

Pixel grid alignment is OK apart from inner parts of the symbols.

What should be fixed is the vertical displacement of the symbols in the ``custom-folder-github`` and ``default-folder-github`` icons in ``16/places`` for all styles.
Symbols should be moved down to **Y=0**. Right now the symbols are exceeding the SVG document canvas.
A significant vertical symbol displacement is also present in the icons in ``32/places`` of style 5.

2021-02-05 18:35 UTC, drakkar1969 commented
Sorry it took me a while to respond to the comments.
Symbol alignment should be fixed now.

2021-02-14 19:41 UTC, palob approved these changes

2021-02-14 19:41 UTC, palob commented
Thank you for the fixes.

2021-04-14 02:27 UTC, Foggalong approved these changes

2021-04-14 02:28 UTC, merged